version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '54321:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
