version: '3.8'
services:
  bookings-db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes:
      - bookings-db:/var/lib/postgresql/data
volumes:
  bookings-db:
    driver: local
